apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: user-service-db
  namespace: user-service
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  instances: 1
  storage:
    size: 1Gi
  bootstrap:
    initdb:
      database: userservice
      owner: userservice