apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: user-service-monitor
  namespace: user-service
  labels:
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app: user-service
  endpoints:
    - port: management
      path: /actuator/prometheus
      interval: 15s