apiVersion: redis.redis.opstreelabs.in/v1beta2
kind: Redis
metadata:
  name: user-service-redis
  namespace: user-service
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  kubernetesConfig:
    image: redis:7
  storage:
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 512Mi