apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: auth-service-db
  namespace: auth-service
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  instances: 1
  storage:
    size: 1Gi
  bootstrap:
    initdb:
      database: authservice
      owner: authservice