apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: auth-service-monitor
  namespace: auth-service
  labels:
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app: auth-service
  endpoints:
    - port: management
      path: /actuator/prometheus
      interval: 15s