apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: main-cluster
  namespace: infrastructure
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  kafka:
    version: 3.8.0
    replicas: 3
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
    storage:
      type: jbod
      volumes:
        - type: persistent-claim
          size: 1Gi
          deleteClaim: false
  entityOperator:
    topicOperator: {}
    userOperator: {}