apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: main-cluster
  namespace: kafka
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  kafka:
    version: 4.1.0
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
  entityOperator:
    topicOperator: {}
    userOperator: {}