apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: main-pool
  namespace: kafka
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  labels:
    strimzi.io/cluster: main-cluster
spec:
  replicas: 3
  roles:
    - broker
    - controller
  storage:
    type: jbod
    volumes:
      - id: 0
        type: persistent-claim
        size: 1Gi
        deleteClaim: false
