apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: api-gateway-monitor
  namespace: api-gateway
  labels:
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app: api-gateway
  endpoints:
    - port: management
      path: /actuator/prometheus
      interval: 15s